/*******************************************************************************/
/* QUERY 1 : List the number of patients who had "tumor,leukemia and ALL"*/
select count(distinct P_ID)
from CLINICAL_FACT
join DISEASE
on (disease.description = 'tumor'
    and
    DISEASE.DS_ID = CLINICAL_FACT.DS_ID);

select count(distinct P_ID)
from CLINICAL_FACT
join DISEASE
on (DISEASE.TYPE = 'leukemia'
    and 
   DISEASE.DS_ID = CLINICAL_FACT.DS_ID);

SELECT COUNT(DISTINCT P_ID)
FROM CLINICAL_FACT
JOIN DISEASE
ON (DISEASE.NAME = 'ALL'
    and
    DISEASE.DS_ID = CLINICAL_FACT.DS_ID);
/******************************************************************************/

/******************************************************************************/
/* QUERY 2 : List the types of drugs applied to patient with tumor*/
SELECT DISTINCT DRUG.TYPE
FROM DRUG
JOIN CLINICAL_FACT
ON DRUG.DR_ID = CLINICAL_FACT.DR_ID
JOIN DISEASE
ON (DISEASE.DESCRIPTION = 'tumor' 
  and 
  DISEASE.DS_ID = CLINICAL_FACT.DS_ID);
/******************************************************************************/

/******************************************************************************/
/* QUERY 3 mRNA values (EXP) for each patient with ALL, cl_id = 00002, mu_id = 001*/
SELECT MICROARRAY_FACT.S_ID, MICROARRAY_FACT.PB_ID,  EXP
FROM MICROARRAY_FACT
JOIN(SELECT DISTINCT S_ID
     FROM CLINICAL_FACT
     JOIN(SELECT P_ID
          FROM CLINICAL_FACT
          JOIN DISEASE
          ON 
          DISEASE.NAME = 'ALL'
          and 
          DISEASE.DS_ID = CLINICAL_FACT.DS_ID)SUB1
     ON (S_ID <> 'null'
          and
         CLINICAL_FACT.P_ID = SUB1.P_ID)
     )SUB2
ON MICROARRAY_FACT.S_ID = SUB2.S_ID
JOIN(SELECT PB_ID
     FROM PROBE
     JOIN GENE_FACT
     ON 
     GENE_FACT.CL_ID = '2'
     and 
     GENE_FACT.U_ID = PROBE.U_ID)SUB3
ON MU_ID = 1
and 
MICROARRAY_FACT.PB_ID = SUB3.PB_ID;

/******************************************************************************/

/******************************************************************************/
/* QUERY 4  t-statistics between patient with ALL and without ALL, with GO_id 0012502*/

/* PATIENT WITH ALL*/
CREATE TABLE TTESTTABLE
AS(
SELECT EXP
FROM MICROARRAY_FACT
JOIN(SELECT DISTINCT S_ID
     FROM CLINICAL_FACT
     JOIN(SELECT P_ID
          FROM CLINICAL_FACT
          JOIN DISEASE
          ON DISEASE.NAME = 'ALL'
          and DISEASE.DS_ID = CLINICAL_FACT.DS_ID)SUB1
     ON S_ID <> 'null'
     and CLINICAL_FACT.P_ID = SUB1.P_ID)SUB2
ON MICROARRAY_FACT.S_ID = SUB2.S_ID
JOIN(SELECT PB_ID
     FROM PROBE
     JOIN GENE_FACT
     ON GENE_FACT.GO_ID = '12502'
     and GENE_FACT.U_ID = PROBE.U_ID)SUB3
ON MICROARRAY_FACT.PB_ID = SUB3.PB_ID);

ALTER TABLE TTESTTABLE
ADD
(DISEASEGROUP VARCHAR2(26) DEFAULT 'ALL' NOT NULL);


/* PATIENT WITHOUT ALL*/
CREATE TABLE TTESTTABLE2
AS(
SELECT EXP
FROM MICROARRAY_FACT
JOIN(SELECT DISTINCT S_ID
     FROM CLINICAL_FACT
     JOIN(SELECT P_ID
          FROM CLINICAL_FACT
          JOIN DISEASE
          ON DISEASE.NAME <> 'ALL'
          and DISEASE.DS_ID = CLINICAL_FACT.DS_ID)SUB1
     ON S_ID <> 'null'
     and CLINICAL_FACT.P_ID = SUB1.P_ID)SUB2
ON MICROARRAY_FACT.S_ID = SUB2.S_ID
JOIN(SELECT PB_ID
     FROM PROBE
     JOIN GENE_FACT
     ON GENE_FACT.GO_ID = '12502'
     and GENE_FACT.U_ID = PROBE.U_ID)SUB3
ON MICROARRAY_FACT.PB_ID = SUB3.PB_ID);

ALTER TABLE TTESTTABLE2
ADD
(DISEASEGROUP VARCHAR2(26) DEFAULT 'NALL' NOT NULL);

/*Calculate the t - statistics */
CREATE TABLE TESTQ4T
AS(
SELECT EXP, DISEASEGROUP
FROM TTESTTABLE
UNION ALL
SELECT EXP, DISEASEGROUP
FROM TTESTTABLE2);

SELECT STATS_T_TEST_INDEP(DISEASEGROUP, EXP) T_OBSERVED
FROM TESTQ4T;

DROP TABLE TTESTTABLE;
DROP TABLE TTESTTABLE2;
DROP TABLE TESTQ4T;
/******************************************************************************/

/******************************************************************************/
/* QUERY 5 F-STATISTICS of exp with go_id = 007154*/

/* PATIENT WITH ALL*/
CREATE TABLE ALLT
AS(
SELECT EXP
FROM MICROARRAY_FACT
JOIN(SELECT DISTINCT S_ID
     FROM CLINICAL_FACT
     JOIN(SELECT P_ID
          FROM CLINICAL_FACT
          JOIN DISEASE
          ON DISEASE.NAME ='ALL'
          and DISEASE.DS_ID = CLINICAL_FACT.DS_ID)SUB1
     ON S_ID <> 'null'
     and CLINICAL_FACT.P_ID = SUB1.P_ID)SUB2
ON MICROARRAY_FACT.S_ID = SUB2.S_ID
JOIN(SELECT PB_ID
     FROM PROBE
     JOIN GENE_FACT
     ON GENE_FACT.GO_ID = '7154'
     and GENE_FACT.U_ID = PROBE.U_ID)SUB3
ON MICROARRAY_FACT.PB_ID = SUB3.PB_ID);

ALTER TABLE ALLT
ADD
(DISEASEGROUP VARCHAR2(26) DEFAULT 'ALL' NOT NULL);

/* PATIENT WITH AML*/
CREATE TABLE AMLT
AS(
SELECT EXP
FROM MICROARRAY_FACT
JOIN(SELECT DISTINCT S_ID
     FROM CLINICAL_FACT
     JOIN(SELECT P_ID
          FROM CLINICAL_FACT
          JOIN DISEASE
          ON DISEASE.NAME ='AML'
          and DISEASE.DS_ID = CLINICAL_FACT.DS_ID)SUB1
     ON S_ID <> 'null'
     and CLINICAL_FACT.P_ID = SUB1.P_ID)SUB2
ON MICROARRAY_FACT.S_ID = SUB2.S_ID
JOIN(SELECT PB_ID
     FROM PROBE
     JOIN GENE_FACT
     ON GENE_FACT.GO_ID = '7154'
     and GENE_FACT.U_ID = PROBE.U_ID)SUB3
ON MICROARRAY_FACT.PB_ID = SUB3.PB_ID);

ALTER TABLE AMLT
ADD
(DISEASEGROUP VARCHAR2(26) DEFAULT 'AML' NOT NULL);

/* PATIENT WITH COLON TUMOR*/
CREATE TABLE CTUMORT
AS(
SELECT EXP
FROM MICROARRAY_FACT
JOIN(SELECT DISTINCT S_ID
     FROM CLINICAL_FACT
     JOIN(SELECT P_ID
          FROM CLINICAL_FACT
          JOIN DISEASE
          ON DISEASE.NAME ='Colon tumor'
          and DISEASE.DS_ID = CLINICAL_FACT.DS_ID)SUB1
     ON S_ID <> 'null'
     and CLINICAL_FACT.P_ID = SUB1.P_ID)SUB2
ON MICROARRAY_FACT.S_ID = SUB2.S_ID
JOIN(SELECT PB_ID
     FROM PROBE
     JOIN GENE_FACT
     ON GENE_FACT.GO_ID = '7154'
     and GENE_FACT.U_ID = PROBE.U_ID)SUB3
ON MICROARRAY_FACT.PB_ID = SUB3.PB_ID);

ALTER TABLE CTUMORT
ADD
(DISEASEGROUP VARCHAR2(26) DEFAULT 'COLON' NOT NULL);

/* PATIENT WITH BREAST TUMOR*/
CREATE TABLE BRTUMORT
AS(
SELECT EXP
FROM MICROARRAY_FACT
JOIN(SELECT DISTINCT S_ID
     FROM CLINICAL_FACT
     JOIN(SELECT P_ID
          FROM CLINICAL_FACT
          JOIN DISEASE
          ON DISEASE.NAME ='Breast tumor'
          and DISEASE.DS_ID = CLINICAL_FACT.DS_ID)SUB1
     ON S_ID <> 'null'
     and CLINICAL_FACT.P_ID = SUB1.P_ID)SUB2
ON MICROARRAY_FACT.S_ID = SUB2.S_ID
JOIN(SELECT PB_ID
     FROM PROBE
     JOIN GENE_FACT
     ON GENE_FACT.U_ID = PROBE.U_ID
     and GENE_FACT.GO_ID = '7154')SUB3
ON MICROARRAY_FACT.PB_ID = SUB3.PB_ID);

ALTER TABLE BRTUMORT
ADD
(DISEASEGROUP VARCHAR2(26) DEFAULT 'BREAST' NOT NULL);

/* CALCULATE F- STATISTICS */
CREATE TABLE FTEST
AS(
SELECT EXP, DISEASEGROUP
FROM ALLT
UNION ALL
SELECT EXP, DISEASEGROUP
FROM AMLT
UNION ALL
SELECT EXP, DISEASEGROUP
FROM CTUMORT
UNION ALL
SELECT EXP, DISEASEGROUP
FROM BRTUMORT
);

SELECT STATS_ONE_WAY_ANOVA(DISEASEGROUP, EXP,'F_RATIO') F_RATIO
FROM FTEST;

DROP TABLE ALLT;
DROP TABLE AMLT;
DROP TABLE CTUMORT;
DROP TABLE BRTUMORT;
DROP TABLE FTEST;
/******************************************************************************/

/******************************************************************************/
/* QUERY 6 */
/******************************************************************************/
CREATE TABLE TEMP1
AS(
SELECT MICROARRAY_FACT.S_ID, MICROARRAY_FACT.PB_ID,EXP
FROM MICROARRAY_FACT
JOIN(SELECT DISTINCT S_ID
     FROM CLINICAL_FACT
     JOIN(SELECT P_ID
          FROM CLINICAL_FACT
          JOIN DISEASE
          ON DISEASE.NAME ='ALL'
          and DISEASE.DS_ID = CLINICAL_FACT.DS_ID)SUB1
     ON S_ID <> 'null'
     and CLINICAL_FACT.P_ID = SUB1.P_ID)SUB2
ON MICROARRAY_FACT.S_ID = SUB2.S_ID
JOIN(SELECT PB_ID
     FROM PROBE
     JOIN GENE_FACT
     ON GENE_FACT.GO_ID = '7154'
     and GENE_FACT.U_ID = PROBE.U_ID)SUB3
ON MICROARRAY_FACT.PB_ID = SUB3.PB_ID);

CREATE TABLE TEMP2
AS(
SELECT MICROARRAY_FACT.S_ID, MICROARRAY_FACT.PB_ID,EXP
FROM MICROARRAY_FACT
JOIN(SELECT DISTINCT S_ID
     FROM CLINICAL_FACT
     JOIN(SELECT P_ID
          FROM CLINICAL_FACT
          JOIN DISEASE
          ON DISEASE.NAME ='AML'
          and DISEASE.DS_ID = CLINICAL_FACT.DS_ID)SUB1
     ON S_ID <> 'null'
     and CLINICAL_FACT.P_ID = SUB1.P_ID)SUB2
ON MICROARRAY_FACT.S_ID = SUB2.S_ID
JOIN(SELECT PB_ID
     FROM PROBE
     JOIN GENE_FACT
     ON GENE_FACT.GO_ID = '7154'
     and GENE_FACT.U_ID = PROBE.U_ID)SUB3
ON MICROARRAY_FACT.PB_ID = SUB3.PB_ID);

DROP TABLE TEMP1;
DROP TABLE TEMP2;

/******************************************************************************/
/* Part III  Question 1 Find the informative Gene for desease ALL*/
/******************************************************************************/
CREATE TABLE ALLTEMP
AS (
SELECT PROBE.U_ID, SUB3.EXP
FROM PROBE
JOIN (SELECT PB_ID, EXP
      FROM MICROARRAY_FACT
      JOIN(SELECT DISTINCT S_ID
           FROM CLINICAL_FACT
           JOIN(SELECT P_ID
                FROM CLINICAL_FACT
                JOIN DISEASE
                ON DISEASE.NAME = 'ALL'
                and DISEASE.DS_ID = CLINICAL_FACT.DS_ID)SUB1
           ON S_ID <> 'null'
           and CLINICAL_FACT.P_ID = SUB1.P_ID)SUB2
      ON MICROARRAY_FACT.S_ID = SUB2.S_ID)SUB3
ON PROBE.PB_ID = SUB3.PB_ID);

ALTER TABLE ALLTEMP
ADD
(DISEASEGROUP VARCHAR2(26) DEFAULT 'ALL' NOT NULL);

CREATE TABLE NOALLTEMP
AS(
SELECT PROBE.U_ID,SUB3.EXP
FROM PROBE
JOIN (SELECT PB_ID, EXP
      FROM MICROARRAY_FACT
      JOIN(SELECT DISTINCT S_ID
           FROM CLINICAL_FACT
           JOIN(SELECT P_ID
                FROM CLINICAL_FACT
                JOIN DISEASE
                ON DISEASE.NAME <> 'ALL'
                and DISEASE.DS_ID = CLINICAL_FACT.DS_ID)SUB1
           ON S_ID <> 'null'
           and CLINICAL_FACT.P_ID = SUB1.P_ID)SUB2
      ON MICROARRAY_FACT.S_ID = SUB2.S_ID)SUB3
ON PROBE.PB_ID = SUB3.PB_ID);

ALTER TABLE NOALLTEMP
ADD
(DISEASEGROUP VARCHAR2(26) DEFAULT 'NOALL' NOT NULL);

CREATE TABLE COMPARETEMP
AS(
SELECT U_ID, DISEASEGROUP, EXP
FROM ALLTEMP
UNION ALL
SELECT U_ID, DISEASEGROUP, EXP
FROM NOALLTEMP
);

CREATE TABLE PVALUETEMP
AS(
SELECT U_ID, STATS_T_TEST_INDEP(DISEASEGROUP, EXP) p_value
FROM COMPARETEMP
GROUP BY U_ID
);

CREATE TABLE ALLINFOGENE
AS(
SELECT U_ID, P_VALUE
FROM PVALUETEMP
WHERE P_VALUE < 0.01);

DROP TABLE PVALUETEMP;
DROP TABLE COMPARETEMP;
DROP TABLE NOALLTEMP;
DROP TABLE ALLTEMP;
/******************************************************************************/

/******************************************************************************/
/* Part III  SQuestion 2 Classify new patient who has ALL*/
/******************************************************************************/
CREATE TABLE TEMP31
AS(
SELECT PROBE.U_ID, SUB3.EXP, SUB3.S_ID
FROM PROBE
JOIN (SELECT PB_ID, EXP, SUB2.S_ID
      FROM MICROARRAY_FACT
      JOIN(SELECT DISTINCT S_ID
           FROM CLINICAL_FACT
           JOIN(SELECT P_ID
                FROM CLINICAL_FACT
                JOIN DISEASE
                ON DISEASE.DS_ID = CLINICAL_FACT.DS_ID
                WHERE DISEASE.NAME = 'ALL')SUB1
           ON CLINICAL_FACT.P_ID = SUB1.P_ID
           WHERE S_ID <> 'null')SUB2
      ON MICROARRAY_FACT.S_ID = SUB2.S_ID)SUB3
ON PROBE.PB_ID = SUB3.PB_ID);

CREATE TABLE TEMP32
AS(
SELECT S_ID, TEMP31.U_ID, EXP
FROM TEMP31
JOIN ALLINFOGENE
ON TEMP31.U_ID = ALLINFOGENE.U_ID);
/*******************************************************************************/
CREATE TABLE TEMP33                /*The Table of the test sample with only informative gene*/
AS(
SELECT TEST_SAMPLE.U_ID, TEST1, TEST2, TEST3, TEST4, TEST5
FROM TEST_SAMPLE
JOIN ALLINFOGENE
ON TEST_SAMPLE.U_ID = ALLINFOGENE.U_ID);

CREATE TABLE RATABLE              /*The Table of the correlation between test patient and the patient with ALL */
AS(
SELECT TEMP32.S_ID, CORR(TEMP32.EXP, TEMP33.TEST1)R1,CORR(TEMP32.EXP, TEMP33.TEST2)R2,CORR(TEMP32.EXP, TEMP33.TEST3)R3,CORR(TEMP32.EXP, TEMP33.TEST4)R4,CORR(TEMP32.EXP, TEMP33.TEST5)R5
FROM TEMP32
JOIN TEMP33
ON TEMP32.U_ID = TEMP33.U_ID
GROUP BY TEMP32.S_ID);

ALTER TABLE RATABLE
ADD
(DISEASEGROUP VARCHAR2(26) DEFAULT 'ALL' NOT NULL);

/*******************************************************************************/
CREATE TABLE TEMP41               /*Patient without All disease informative gene exp*/
AS(
SELECT PROBE.U_ID, SUB3.EXP, SUB3.S_ID
FROM PROBE
JOIN (SELECT PB_ID, EXP, SUB2.S_ID
      FROM MICROARRAY_FACT
      JOIN(SELECT DISTINCT S_ID
           FROM CLINICAL_FACT
           JOIN(SELECT P_ID
                FROM CLINICAL_FACT
                JOIN DISEASE
                ON DISEASE.NAME <> 'ALL'
                and DISEASE.DS_ID = CLINICAL_FACT.DS_ID)SUB1
           ON S_ID <> 'null'
           and CLINICAL_FACT.P_ID = SUB1.P_ID)SUB2
      ON MICROARRAY_FACT.S_ID = SUB2.S_ID)SUB3
ON PROBE.PB_ID = SUB3.PB_ID);

CREATE TABLE TEMP42
AS(
SELECT S_ID, TEMP41.U_ID, EXP
FROM TEMP41
JOIN ALLINFOGENE
ON TEMP41.U_ID = ALLINFOGENE.U_ID);

CREATE TABLE RBTABLE
AS(
SELECT TEMP42.S_ID, CORR(TEMP42.EXP, TEMP33.TEST1)R1,CORR(TEMP42.EXP, TEMP33.TEST2)R2,CORR(TEMP42.EXP, TEMP33.TEST3)R3,CORR(TEMP42.EXP, TEMP33.TEST4)R4,CORR(TEMP42.EXP, TEMP33.TEST5)R5
FROM TEMP42
JOIN TEMP33
ON TEMP42.U_ID = TEMP33.U_ID
GROUP BY TEMP42.S_ID);

ALTER TABLE RBTABLE
ADD
(DISEASEGROUP VARCHAR2(26) DEFAULT 'NOALL' NOT NULL);

CREATE TABLE RABTABLE
AS(
SELECT DISEASEGROUP, R1, R2, R3, R4, R5
FROM RATABLE
UNION ALL
SELECT DISEASEGROUP, R1, R2, R3, R4, R5
FROM RBTABLE);

SELECT STATS_T_TEST_INDEP(DISEASEGROUP, R1)PATIEN1, STATS_T_TEST_INDEP(DISEASEGROUP, R2)PATIENT2, STATS_T_TEST_INDEP(DISEASEGROUP, R3)PATIENT3, STATS_T_TEST_INDEP(DISEASEGROUP, R4)PATIENT4, STATS_T_TEST_INDEP(DISEASEGROUP, R5)PATIENT5
FROM RABTABLE;

DROP TABLE TEMP31;
DROP TABLE TEMP32;
DROP TABLE TEMP33;
DROP TABLE TEMP41;
DROP TABLE TEMP42;
DROP TABLE RATABLE;
DROP TABLE RBTABLE;
DROP TABLE RABTABLE;
DROP TABLE ALLINFOGENE;
/*******************************************************************************/






  







