--------------------------------------------------------
--  File created - Tuesday-October-04-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BRTUMORT
--------------------------------------------------------

  CREATE TABLE "VICKYZHE"."BRTUMORT" 
   (	"EXP" NUMBER(3,0), 
	"DISEASEGROUP" VARCHAR2(26 BYTE) DEFAULT 'BREAST'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CSE601" ;
REM INSERTING into VICKYZHE.BRTUMORT
SET DEFINE OFF;
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (7,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (171,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (129,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (164,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (142,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (189,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (172,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (6,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (67,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (136,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (167,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (65,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (94,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (136,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (185,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (147,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (193,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (173,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (6,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (77,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (97,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (44,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (22,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (158,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (52,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (28,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (81,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (13,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (9,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (12,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (133,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (47,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (136,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (5,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (104,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (55,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (30,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (121,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (127,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (120,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (124,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (109,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (91,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (53,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (18,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (157,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (117,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (140,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (193,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (102,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (23,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (74,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (40,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (93,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (190,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (148,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (161,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (84,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (71,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (179,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (53,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (200,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (73,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (6,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (18,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (181,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (98,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (82,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (88,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (119,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (100,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (164,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (181,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (76,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (192,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (130,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (131,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (177,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (194,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (195,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (129,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (107,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (196,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (50,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (129,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (125,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (162,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (169,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (186,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (6,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (77,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (55,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (18,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (70,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (88,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (195,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (90,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (81,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (4,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (184,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (32,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (77,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (50,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (197,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (143,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (51,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (30,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (108,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (24,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (139,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (121,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (63,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (102,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (190,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (59,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (116,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (95,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (130,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (73,'BREAST');
Insert into VICKYZHE.BRTUMORT (EXP,DISEASEGROUP) values (43,'BREAST');
--------------------------------------------------------
--  Constraints for Table BRTUMORT
--------------------------------------------------------

  ALTER TABLE "VICKYZHE"."BRTUMORT" MODIFY ("DISEASEGROUP" NOT NULL ENABLE);
