#!/bin/sh

a=0

while [ $a -lt 3 ]
do
	echo $a
	hadoop jar /usr/local/Cellar/hadoop/2.7.2/libexec/share/hadoop/tools/lib/hadoop-streaming-2.7.2.jar -file mapper.py -mapper mapper.py -file reducer.py -reducer reducer.py -input /user/601cse/new_dataset_1.txt -output /user/601cse/newData1Output
	cat new1Centroids.txt
	hadoop dfs -rm -r /user/601cse/newData1Output

	a=`expr $a + 1`
done

python visualize.py