#!/bin/sh

./randCentroids.py new_dataset_2.txt new2Centroids.txt 2
./getClusterAssignments.py new_dataset_2.txt new2Assignments.txt
hadoop dfs -rm /user/601cse/new*
hadoop dfs -copyFromLocal new2* /user/601cse
hadoop dfs -copyFromLocal new_dataset_2.txt /user/601cse