#!/bin/sh

a=0

while [ $a -lt 15 ]
do
	hadoop jar /usr/local/Cellar/hadoop/2.7.2/libexec/share/hadoop/tools/lib/hadoop-streaming-2.7.2.jar -file mapper.py -mapper mapper.py -file reducer.py -reducer reducer.py -input /user/601cse/cho.txt -output /user/601cse/cho_outputs
	if [$a -ls 14]
	then
		hadoop dfs -rm -r /user/601cse/cho_outputs
	fi
	a=`expr $a + 1`
done